#!/usr/bin/env bash

function display_info() {
    domain=$1
    subdomain=$2
    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    for sub in "${subdomains[@]}"; do
        record=$(dig "$sub.$domain" +short)
        record_type=$(dig "$sub.$domain" +short | awk -F' ' '{print $2}')
        echo "The subdomain $sub is a $record_type record and points to $record"
    done
}

display_info "$1" "$2"

