#!/usr/bin/env bash

# Define the key file path
key_file=~/.ssh/school

# Generate the RSA key pair with passphrase
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

# Output success message
echo "RSA key pair created successfully with the passphrase 'betty'. Private key stored in $key_file."

